name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install wasm-pack
      run: cargo install wasm-pack
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - name: Build Wasm
      run: wasm-pack build
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
    - name: Run Wasm tests
      run: wasm-pack test --headless --chrome
    
  
    
